### ISSUE TITLE
Can't print - AttributeError: 'Settings' object has no attribute 'set_bool'

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#102]
```
2016-02-29 18:06:49,065 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.0.dev888+geacd9f7-py2.7.egg/octoprint/util/comm.py", line 1491, in _readline
    ret = self._serial.readline()
  File "build/bdist.linux-armv7l/egg/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2016-02-29 18:07:15,720 - octoprint - ERROR - Exception on /api/plugin/m3dfio [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.0.dev888+geacd9f7-py2.7.egg/octoprint/server/util/flask.py", line 709, in decorated_view
    return flask.ext.login.login_required(func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.2.2-py2.7.egg/flask_login.py", line 637, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.0.dev888+geacd9f7-py2.7.egg/octoprint/server/api/__init__.py", line 97, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint_M3DFio-0.27.20160223-py2.7.egg/octoprint_m3dfio/__init__.py", line 1998, in on_api_command
    self._settings.set_bool(["UseWaveBondingPreprocessor"], bool(values["useWaveBondingPreprocessor"]))
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.0.dev888+geacd9f7-py2.7.egg/octoprint/plugin/__init__.py", line 526, in __getattr__
    return getattr(self.settings, item)
AttributeError: 'Settings' object has no attribute 'set_bool'
2016-02-29 18:07:15,807 - tornado.access - ERROR - 500 POST /api/plugin/m3dfio (127.0.0.1) 126.56ms
```

**Comment by donovan6000** [comment]
I assumed it was set_bool. Thanks for the set_boolean fix
